language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter --coverage-report=./tests/storage/logs/test-reports/clover.xml

addons:
  code_climate:
    repo_token: CODECLIMATE_REPO_TOKEN
